# Github workflow for Python script
name: update_worklog

on:
    workflow_dispatch:
    schedule:
        - cron: '30 13 * * *'

jobs:
    update_worklog:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '21.x'

            - name: Install dependencies
              run: npm install

            - name: Run update_worklog javascript
              run: node update_worklog.js
              env:
                KRONOS_EMAIL: ${{ secrets.KRONOS_EMAIL }}
                KRONOS_PASSWORD: ${{ secrets.KRONOS_PASSWORD }}

            - name: PingMe On Pushbullet
              uses: kha7iq/pingme-action@v1
              with:
                service: pushbullet
              env:
                PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
                PUSHBULLET_DEVICE: ${{ secrets.PUSHBULLET_DEVICE }}
                PUSHBULLET_TITLE: 'Kronos Worklog Updated'
                PUSHBULLET_MESSAGE: |
                  Event is triggered by ${{ github.event_name }}
                  Workflow Log: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
